// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC14HIFF5zasRR9J5bvKrTcpgvkXOsNVpQ',
    appId: '1:621252605580:web:d4dbf19347e2038e632da9',
    messagingSenderId: '621252605580',
    projectId: 'graduationproject-dc2e2',
    authDomain: 'graduationproject-dc2e2.firebaseapp.com',
    storageBucket: 'graduationproject-dc2e2.appspot.com',
    measurementId: 'G-7CRMWL6J53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHBGIOtO4h4JBLdFyDA--uTQwAINlIrM',
    appId: '1:621252605580:android:31d09466a2ae7f55632da9',
    messagingSenderId: '621252605580',
    projectId: 'graduationproject-dc2e2',
    storageBucket: 'graduationproject-dc2e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEuIMXIFczgyw3UKC5PPy-BtlR7dgMV9M',
    appId: '1:621252605580:ios:7c1f7f4c42abb814632da9',
    messagingSenderId: '621252605580',
    projectId: 'graduationproject-dc2e2',
    storageBucket: 'graduationproject-dc2e2.appspot.com',
    iosClientId:
        '621252605580-g3l86mddeg9p6du3gcv5a78vgkiefaqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEuIMXIFczgyw3UKC5PPy-BtlR7dgMV9M',
    appId: '1:621252605580:ios:7c1f7f4c42abb814632da9',
    messagingSenderId: '621252605580',
    projectId: 'graduationproject-dc2e2',
    storageBucket: 'graduationproject-dc2e2.appspot.com',
    iosClientId:
        '621252605580-g3l86mddeg9p6du3gcv5a78vgkiefaqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
